### ISSUE TITLE
🚀[Feature] 로직 구현 및 api 연결

### ISSUE THREAD

**Issue by naarang** [GDSC-snowflowerthon/Snowcare-team06-web#16]
## 🔨 Describe

- 로직 구현 및 api 연결

## ✅ Tasks
- [ ] api 폴더 정리
- [ ] api 연결 및 로직 구현
- [ ] 마이페이지 디자인 수정
